# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 05:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
                ('intencion', models.CharField(max_length=30)),
                ('precio', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('negociable', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['venta', 'compras'], size=None)),
                ('contacto', django.contrib.postgres.fields.jsonb.JSONField(default={'eder': 'eder'})),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.SubCategoria')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
